name: Build Client Prd

on:
  push:
    branches:
      - main  # 원하는 브랜치로 변경 가능

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .env.production
        run: echo "${{ secrets.ENV }}" > .env.production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t ariel250225/crypto-tracker-node-api:1.0.0 --push .

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ariel250225/crypto-tracker-node-api:1.0.0
            docker stop crypto-tracker-node-api || true
            docker rm crypto-tracker-node-api || true
            docker run -d -p 3000:3000 --restart unless-stopped -v /home/ec2-user/crypto-tracker-node-api-log:/app/log --name crypto-tracker-node-api ariel250225/crypto-tracker-node-api:1.0.0
